version: '3.9'
services:

  isa-client:
    image: isa-client
    ports:
      - "3000:3000"
    build:
      context: ../ISA-client
      dockerfile: Dockerfile

  isa-server:
    image: isa-server
    restart: on-failure
    network_mode: "host"
#    ports:
#      - "8080:8080"
    depends_on:
        isa-postgres:
          condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile

  isa-postgres:
    image: postgres
    restart: on-failure
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prahapodoli
      - POSTGRES_DB=goldSilver
      # solves problem of incompatible password hashing functions (related to pg_isready)
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    healthcheck:
      # -U postgres solves problem with missing root user
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    external: false

#  sudo docker compose build/run/restart isa-client
#  sudo docker compose down
#  sudo docker compose up -d
#  sudo docker compose logs isa-server

#  sudo docker exec -it <container_id_or_name> psql -U <username> -d <database_name>
#  ALTER USER postgres PASSWORD 'postgres';
