

###

GET http://localhost:8080/api/v2/product/metal/platinum

### SCRAP

GET http://localhost:8080/api/v2/scrap/all
###

GET http://localhost:8080/api/v2/scrap/serenity
###

GET http://localhost:8080/api/v2/scrap/links
###

GET http://localhost:8080/api/v2/scrap/products
###

GET http://localhost:8080/api/v2/scrap/dealer/zlataky
###

### PORTFOLIO

GET http://localhost:8080/api/v2/portfolio/id/3194
###

GET http://localhost:8080/api/v2/portfolio/owner/Carlos
###

GET http://localhost:8080/api/v2/portfolio/owner/NO
###

GET http://localhost:8080/api/v2/portfolio/
###

GET http://localhost:8080/api/v2/portfolio/31
###

POST http://localhost:8080/api/v2/portfolio
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"owner": "Ga", "investmentIds": []}

################################################

DELETE http://localhost:8080/api/v2/portfolio/4
###

GET http://localhost:8080/api/v2/link/param?dealer=SILVERUM
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Charset: UTF-8

###

GET http://localhost:8080/api/v2/scrap/links/param?dealer=SILVERUM
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Charset: UTF-8

###

GET http://localhost:8080/api/v2/scrap/param
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Charset: UTF-8

###

GET http://localhost:8080/api/v2/scrap/dealer?dealer=SILVERUM
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Charset: UTF-8

###

GET http://localhost:8080/api/v2/scrap/products
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Charset: UTF-8