package home.holymiko.InvestmentScraperApp.Server.Type.Enum;

public enum Producer {
    // DB table product modify checks
    ARGOR_HERAEUS, HERAEUS, MUNZE_OSTERREICH, PERTH_MINT, VALCAMBI,
    PAMP, MEXICO_MINT, ROYAL_CANADIAN_MINT, CHINA_MINT, ROYAL_MINT_UK,
    SOUTH_AFRICAN_MINT, UNITED_STATES_MINT, BAVARIAN_STATE_MINT, POBJOY_MINT,
    LEIPZIGER_EDELMETALLVERARBEITUNG_GMBH, UMICORE, SCOTTSDALE_MINT, SUNSHINE_MINT, SILVER_TOWNE,
    JOHNSON_MATTHEY, GOLDEN_STATE_MINT, COMEX, PRESSBURG_MINT, CNB, CESKA_MINCOVNA, C_HAFNER,
    NEW_ZEALAND_MINT, BESSERGOLD, KREMNICA, BH_MAYER_MINT, BULMINT, LBMA, METALOR
}

