version: '3'
services:
  postgres:
    restart: always
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goldSilver
    volumes:
      - postgres_data:/var/lib/postgrsql/data
volumes:
  postgres_data:
    external: false