package home.holymiko.InvestmentScraperApp.Server.Enum;

public enum Producer {
    UNKNOWN, ARGOR_HERAEUS, HERAEUS, MUNZE_OSTERREICH, PERTH_MINT, VALCAMBI,
    PAMP, MEXICO_MINT, ROYAL_CANADIAN_MINT, CHINA_MINT, ROYAL_MINT_UK,
    SOUTH_AFRICAN_MINT, UNITED_STATES_MINT, BAVARIAN_STATE_MINT, POBJOY_MINT
}

